---

   - name: validate devices can ping their bgp peers 
     junos_ping:
      provider: "{{ credentials }}"
      acceptable_percent_loss: 10
      count: 10
      dest_ip: "{{ item.peer_ip }}"
     with_items:
     - "{{ BGP_neighbors }}"
     when: (BGP_neighbors) is defined
     ignore_errors: "{{ audit.mode.loose }}"

   - name: validate bgp sessions are Established
     junos_command:
      provider: "{{ credentials }}"
      display: 'xml'
      commands:
       - show bgp neighbor "{{ item.peer_ip }}"
      waitfor:
       - "result[0]['rpc-reply']['bgp-information']['bgp-peer']['peer-state'] eq 'Established'"
      retries: 3
      interval: 3
     with_items:
     - "{{ BGP_neighbors }}"
     when: (BGP_neighbors) is defined 
     ignore_errors: "{{ audit.mode.loose }}"

   - name: validate the number of BGP routes received 
     junos_command:
       provider: "{{ credentials }}"
       display: 'xml'
       commands:
         - show route receive-protocol bgp "{{ item.peer_ip }}" table inet.0
       waitfor:
         - "result[0]['rpc-reply']['route-information']['route-table']['total-route-count'] gt {{ item.number_of_routes_learnt_greater_than }}"
       retries: 3
       interval: 3
     with_items:
     - "{{ BGP_neighbors }}"
     when: (BGP_neighbors) is defined 
     ignore_errors: "{{ audit.mode.loose }}"

