host_name: leaf2
loopback: 100.100.30.2
local_asn: 65302
local_ip: 10.40.2.1
neighbors:
   - interface: em3
     name: to spine1
     asn: 65201
     peer_ip: 192.168.10.2
     local_ip: 192.168.10.3
   - interface: em4
     name: to spine2
     asn: 65202
     peer_ip: 192.168.11.2
     local_ip: 192.168.11.3
