
FROM ubuntu:18.04

MAINTAINER Mohammad Tahir <tahiritian@gmail.com> 

ADD . /

WORKDIR /

RUN apt-get update && apt-get -y upgrade && \
    apt-get install -y python-pip


RUN pip install -r requirements.txt  && \
    ansible-galaxy install -r requirements.ansible.yaml


ENTRYPOINT sh ./microservice_validate_network_state.sh 
