---
  - name: validate vlan
    junos_command:
      provider: "{{ credentials }}"
      display: 'xml'
      commands:
       - "show vlans {{ item.name }}"
      waitfor:
       - "result[0]['rpc-reply']['l2ng-l2ald-vlan-instance-information']['l2ng-l2ald-vlan-instance-group']['l2ng-l2rtb-vlan-name'] eq {{ item.name }}"
    with_items: "{{ vlans }}"
    when: (vlans is defined)
    ignore_errors: "{{ audit.mode.loose }}"

