---
- name: install config
  hosts: juniper
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars_prompt:
    - name: ADMUSER
      prompt: Username
      private: no
    - name: ADMPASS
      prompt: Password
      private: yes
  vars:
    - console_port: 7006
    - console_server: core2
  tasks:
    - name: Install configuration on Junos device
      junos_install_config:
        host: "{{ console_server }}"
        user: "{{ ADMUSER }}"
        passwd: "{{ ADMPASS }}"
        mode: "telnet"
        port: "{{ console_port }}"
        file: /etc/ansible/cmds-files/config.conf
    - name: Commit changes
      junos_commit:
        host: "{{ console_server }}"
        user: "{{ ADMUSER }}"
        passwd: "{{ ADMPASS }}"
        mode: "telnet"
        port: "{{ console_port }}"
