---
   - name: validate lldp neighbors are the ones we excpect
     junos_command:
      provider: "{{ credentials }}"
      display: 'xml'
      commands:
       - show lldp neighbors interface "{{ item.local_interface }}"
      waitfor:
       - "result[0]['rpc-reply']['lldp-neighbors-information']['lldp-neighbor-information']['lldp-remote-system-name'] == {{ item.remote_name }}"
      retries: 3
      interval: 3
     with_items:
     - "{{ LLDP_neighbors }}"
     when: (item) is defined
     ignore_errors: "{{ audit.mode.loose }}"
